use cri_adx_proc::create_static;

create_static!(CRIATOMEXPLAYER_CREATE, u8);
create_static!(CRIATOMEXPLAYER_START, u8);
create_static!(CRIATOMEXPLAYER_SETFORMAT, u8);
create_static!(CRIATOMEXPLAYER_SETNUMCHANNELS, u8);
create_static!(CRIATOMEXPLAYER_SETSAMPLINGRATE, u8);
create_static!(CRIATOMEXPLAYER_SETCATEGORYBYID, u8);
create_static!(CRIATOMEXPLAYER_SETVOLUME, u8);
create_static!(CRIATOMEXPLAYER_RESETPARAMETERS, u8);
create_static!(CRIATOMEXPLAYER_SETFILE, u8);
create_static!(CRIATOMEXPLAYER_SETCUEID, u8);
create_static!(CRIATOMEXPLAYER_SETWAVEID, u8);
create_static!(CRIATOMEXACB_LOADACBDATA, u8);
create_static!(CRIATOMAWB_LOADTOC, u8);
create_static!(CRIATOMEXCATEGORY_GETVOLUMEBYID, u8);
create_static!(CRIATOMEXCATEGORY_SETVOLUMEBYID, u8);
create_static!(CRIATOMEXACB_GETCUEINFOBYID, u8);
